export const STATION = {
	id: "",
	name: "",
	vicinity: "",
	country: "",
	location: "",
	googleID: "",
	facilities: {
		WC: "1",
		Market: "1",
		CarWash: "1",
		TireRepair: "0",
		Mechanic: "0",
		Restaurant: "0",
		ParkSpot: "0",
		ATM: "0",
		Motel: "0",
	},
	logoURL: "",
	gasolinePrice: 0,
	dieselPrice: 0,
	lpgPrice: 0,
	electricityPrice: 0,
	lastUpdated: "",
}
